### PR TITLE
[datadog_teams] Add new datasource 

### LINKED ISSUE #2217: data source datadog_team: Error: filter keyword returned more than one result, use more specific search criteria
### Datadog Terraform Provider Version

v3.34.0

### Terraform Version

v1.5.6

### What resources or data sources are affected?

data source datadog_team

### Terraform Configuration Files

```hcl
// Validate if var.team is an existing Datadog team

data "datadog_team" "validate_team" {
 filter_keyword = var.team
}
```

### Relevant debug or panic output

 Error: filter keyword returned more than one result, use more specific search criteria

### Expected Behavior

 Using datadog_team with filter_keyword on teams with similar names such as  'engineering'  & 'data-engineering'  either brings all the matching results without errors, or brings the exact match for the keyword.  

### Actual Behavior

Error: filter keyword returned more than one result, use more specific search criteria

### Steps to Reproduce

1) Create three teams in Datadog UI, two of the team names with matching substrings such as  'engineering'  & 'data-engineering' 
2) From terraform create a data source using `datadog_team`  and filter_keyword = "engineering"
3) After running terraform plan you will receive the error "Error: filter keyword returned more than one result, use more specific search criteria"
4)  Change filter_keyword="thirdteam" 
5) After running terraform plan you will not receive any errors 

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by Supam**
resolves #2217 

This PR adds the `data_source_datadog_teams` data source.

Remark : we have tested manually the `filter_me` field as there is no datasource to "introspect" the authenticated user, we can't create a group where the user executing the tests is added in the newly created team.

### CODE REVIEW

**Review by buraizu — APPROVED** [review]

File: datadog/fwprovider/data_source_datadog_teams.go [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+
+	pageSize := 100
+	pageNumber := int64(0)
+	optionalParams.WithPageSize(int64(pageSize))
+
+	var teams []datadogV2.Team
+	for {
+		optionalParams.WithPageNumber(pageNumber)
+
+		ddResp, _, err := d.Api.ListTeams(d.Auth, optionalParams)
```
Comment (fpighi) [inline datadog/fwprovider/data_source_datadog_teams.go:116]: It might be worth passing a `sort` parameter as well, so we can rely on a stable order within the resulting list of teams that ends up in state.

**Review by dshivara — DISMISSED** [review]

File: datadog/fwprovider/data_source_datadog_teams.go [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+			response.Diagnostics.Append(utils.FrameworkErrorDiag(err, "error getting teams"))
+			return
+		}
+
+		teams = append(teams, ddResp.GetData()...)
+		if len(ddResp.GetData()) < pageSize {
+			break
+		}
+		pageNumber++
+	}
```
Comment (ecdatadog) [inline datadog/fwprovider/data_source_datadog_teams.go:128]: 2 remarks : 
1) Rather than reimplementing pagination, the api clients provides a d.API.ListTeamsWithPagination(d.Auth, optionalParams) that returns a read channel 
2) for info, [for some APIs](https://dd.slack.com/archives/C8E85JEGH/p1739200094686509), the end condition (len(items) != pageSize) is broken due to GRACE but it shouldn't be the case for Teams

**Review by ecdatadog — COMMENTED** [review]
Do we want to include these files in this PR 
* .generator/V2/openapi.yaml 
* static-analysis.datadog.yml

**Review by ecdatadog — APPROVED** [review]
LGTM !

**Review by amaskara-dd — APPROVED** [review]
