### PR TITLE
Handle crash in timeseries_definition

### LINKED ISSUE #861: Passing an empty strings to timeseries_definition.metadata attributes panics
### Terraform Version

terraform -version
Terraform v0.14.4
+ provider registry.terraform.io/datadog/datadog v2.20.0

terraform -version
Terraform v0.14.5
+ provider registry.terraform.io/datadog/datadog v2.20.0
### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_dashboard

### Terraform Configuration Files

```hcl
resource "datadog_dashboard" "beacon" {
  title        = "Beacon Service"
  description  = "A Datadog Dashboard "
  layout_type  = "ordered"
  is_read_only = true

   widget {
    timeseries_definition {
      show_legend = false
      title       = "CPU Utilization"

      request {
        display_type = "line"
        q            = "top(avg:docker.cpu.usage{image_name:onlydole/beacon} by {docker_image,container_id}, 10, 'mean', 'desc')"

        style {
          line_type  = "solid"
          line_width = "normal"
          palette    = "dog_classic"
        }

        metadata {
            // causes panic: panic: interface conversion: interface {} is nil, not map[string]interface {}
            // See https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go#L4494
            expression = ""
        }
      }

      yaxis {
        include_zero = true
        max          = "auto"
        min          = "auto"
        scale        = "linear"
      }
    }
  }
}
```

### Panic Output

[crash.log](https://gist.github.com/CrankyDragon/6e3d3a9291cd05cb6eeed3f194d16813)

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by therve**
Terraform removes empty values under us, we need to take that into
account when casting objects.

Closes #861

### CODE REVIEW

File: datadog/resource_datadog_dashboard.go [hunk 1]
```diff
@@ -4491,7 +4491,10 @@ func buildDatadogTimeseriesRequests(terraformRequests *[]interface{}) *[]datadog
 		if terraformMetadataList, ok := terraformRequest["metadata"].([]interface{}); ok && len(terraformMetadataList) > 0 {
 			datadogMetadataList := make([]datadogV1.TimeseriesWidgetRequestMetadata, len(terraformMetadataList))
 			for i, m := range terraformMetadataList {
-				metadata := m.(map[string]interface{})
+				metadata, ok := m.(map[string]interface{})
+				if !ok {
+					continue
+				}
```
Comment (zippolyte) [inline datadog/resource_datadog_dashboard.go:4497]: any chance this can create non empty plans ? If something is specified in the config but we completely ignore it ?

Comment (zippolyte) [reply datadog/resource_datadog_dashboard.go:4497]: Let's add an empty value in one of the test configs to try it out too

**Review by zippolyte — APPROVED** [review]
