### PR TITLE
[datadog_logs_metric][datadog_metric_metadata] Normalize invalid metric name

### LINKED ISSUE #2432: Provider produced inconsistent final plan - Replacing `-` with `_` in names of `datadog_metric_metadata.metric_description`
### Datadog Terraform Provider Version

v3.39.0

### Terraform Version

v1.7

### What resources or data sources are affected?

`datadog_metric_metadata.metric_description`

### Terraform Configuration Files

```hcl
locals {
  functions = {
    ...
    "install-plugin" = {
      url_pattern = "..."
    },
    ...
  }
}

module "http_metrics_per_function" {
  source   = "./modules/custom_metric"
  for_each = local.functions
  ...
  name            = "orbiter.${each.key}.http.request"
  ...
}

resource "datadog_logs_metric" "this" {
  name = var.name
  ...
}

resource "datadog_metric_metadata" "metric_description" {
  metric          = datadog_logs_metric.this.name
  ...
}
```

### Relevant debug or panic output
```
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.http_metrics_per_function["install-plugin"].datadog_metric_metadata.metric_description
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/datadog/datadog" produced an invalid new value for
│ .metric: was cty.StringVal("orbiter.install-plugin.http.request"), but now
│ cty.StringVal("orbiter.install_plugin.http.request").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
### Expected Behavior

The Terraform should have applied correctly with the name `install-plugin` rather than `install_plugin`

### Actual Behavior

The Terraform errored with the error given above.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by nkzou**
APITL-922
Resolves #2432 

Normalize metric names using the same function the backend uses

### CODE REVIEW

File: datadog/internal/validators/validators.go [hunk 1]
```diff
@@ -159,6 +159,40 @@ func ValidateNonEmptyStrings(v any, p cty.Path) diag.Diagnostics {
...
+
+	// Validate metric name length
+	if len(value) > 200 {
+		diags = append(diags, diag.Diagnostic{
+			Severity:      diag.Warning,
+			Summary:       "Invalid value",
+			Detail:        "Metric name cannot exceed 200 characters.",
+			AttributePath: p,
+		})
+	}
```
Comment (nkzou) [inline datadog/internal/validators/validators.go:192]:
```suggestion
```

**Review by jack-edmonds-dd — APPROVED** [review]
