### PR TITLE
[datadog_service_definition_yaml] Add ordering of contacts in state func

### LINKED ISSUE #1778: Order of `datadog_service_definition_yaml` of yaml `contacts` keeps changing
### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
terraform 1.3.7
datadog v3.21.0
```

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_service_definition_yaml

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
resource "datadog_service_definition_yaml" "service_definition" {
  service_definition = <<-EOT
    contacts:
    - contact: snip
      name: snip
      type: slack
    - contact: snip
      name: snip
      type: email
    EOT
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

What should have happened?

It should have been a `no-op`

### Actual Behavior

What actually happened?

Seems that the type:email gets ordered first and then the type:slack 

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. See the above hcl
1. Run `terraform plan`
1. Run `terraform apply`
2. Run `terraform plan` to see the reodering

### Important Factoids

N/A

### References

N/A

### PR DESCRIPTION
**Pull request by nkzou**
Fixes drift when a service definition yaml's contact field gets sorted by the backend. Closes #1778

### CODE REVIEW

File: datadog/resource_datadog_service_definition_yaml.go [hunk 1]
```diff
@@ -125,6 +125,37 @@ func prepServiceDefinitionResource(attrMap map[string]interface{}) map[string]in
...
+
+			sort.SliceStable(sorted_contacts, func(i, j int) bool {
+				type_l_val, type_l_ok := sorted_contacts[i]["type"]
+				type_r_val, type_r_ok := sorted_contacts[j]["type"]
+				if !(type_l_val == type_r_val) && type_l_ok && type_r_ok {
+					return type_l_val.(string) < type_r_val.(string)
+				}
+				contact_l_val, contact_l_ok := sorted_contacts[i]["contact"]
+				contact_r_val, contact_r_ok := sorted_contacts[j]["contact"]
+				if !(contact_l_val == contact_r_val) && contact_l_ok && contact_r_ok {
```
Comment (therve) [inline datadog/resource_datadog_service_definition_yaml.go:145]:
```suggestion
				if contact_l_val != contact_r_val && contact_l_ok && contact_r_ok {
```

**Review by therve — COMMENTED** [review]
One run of goimports and we're good to go.

**Review by therve — APPROVED** [review]

**Review by GalenPickard — APPROVED** [review]
